# Outputs for Development Environment

output "control_plane_ips" {
  description = "Public IPs of control plane nodes"
  value       = module.instances.control_plane_ips
}

output "worker_ips" {
  description = "Public IPs of worker nodes"
  value       = module.instances.worker_ips
}

output "private_network_id" {
  description = "Private network ID"
  value       = module.networking.private_network_id
}

output "ansible_inventory" {
  description = "Ansible inventory"
  value       = module.instances.ansible_inventory
  sensitive   = true
}

output "backup_container" {
  description = "Backup container name"
  value       = module.storage.backup_container_name
}

output "s3_credentials" {
  description = "S3 credentials for backups"
  value = {
    access_key = module.storage.s3_access_key
    secret_key = module.storage.s3_secret_key
  }
  sensitive = true
}

# Save Ansible inventory to file
resource "local_file" "ansible_inventory" {
  content  = module.instances.ansible_inventory
  filename = "${path.module}/../../../ansible/inventory/dev.yml"

  file_permission = "0644"
}

# Kubeconfig will be generated by Ansible
output "kubeconfig_path" {
  description = "Path to kubeconfig file (generated by Ansible)"
  value       = "~/.kube/koprogo-dev"
}

# Connection info
output "connect_info" {
  description = "Connection information"
  value = <<-EOT
    Development Environment Created!

    Control Plane:
    ${join("\n    ", formatlist("  - %s (ssh ubuntu@%s)", module.instances.control_plane_names, module.instances.control_plane_ips))}

    Workers:
    ${join("\n    ", formatlist("  - %s (ssh ubuntu@%s)", module.instances.worker_names, module.instances.worker_ips))}

    Next Steps:
    1. Run Ansible: cd ../../ansible && ansible-playbook -i inventory/dev.yml playbooks/site.yml
    2. Get kubeconfig: export KUBECONFIG=~/.kube/koprogo-dev
    3. Check cluster: kubectl get nodes

    Estimated Monthly Cost: ~30€
  EOT
}
