---
# Handlers for security role

- name: restart_sshd
  systemd:
    name: sshd
    state: restarted

- name: restart_fail2ban
  systemd:
    name: fail2ban
    state: restarted

- name: restart_auditd
  command: service auditd restart
