# docker-compose.override.yml
# Ce fichier est automatiquement chargé par docker-compose en développement
# Il override les configurations de docker-compose.yml

services:
  api:
    volumes:
      # En dev: monte le code source pour le hot-reload (mais le binaire sera dans target/)
      - ./backend/src:/app/src:ro
      - ./backend/migrations:/app/migrations:ro
      - cargo_cache:/usr/local/cargo
    command: >
      sh -c "
      echo 'Dev mode: Using compiled binary from image';
      /app/koprogo-api
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev -- --host 0.0.0.0
    volumes:
      # En dev: monte le code source pour le hot-reload
      - ./frontend:/app
      - /app/node_modules
      - /app/dist
    environment:
      PUBLIC_API_URL: http://localhost:8080
