# Traefik Static Configuration - PRODUCTION
# Configuration sécurisée pour production (sans dashboard)

# API and Dashboard - DÉSACTIVÉ EN PRODUCTION
api:
  dashboard: false
  insecure: false

# Entrypoints
entryPoints:
  web:
    address: ":80"
    # Pour activer HTTPS plus tard, décommenter:
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  # Pour HTTPS (Let's Encrypt), décommenter:
  # websecure:
  #   address: ":443"

# Docker provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Seuls les services avec traefik.enable=true seront exposés
    network: koprogo-network

# Logging - Niveau WARNING en production
log:
  level: info
  format: json

# Access logs - Format JSON pour analyse
accessLog:
  format: json
  fields:
    headers:
      defaultMode: drop  # Ne pas logger les headers par défaut (sécurité)

# Metrics (optionnel - à activer si monitoring Prometheus)
# metrics:
#   prometheus:
#     addEntryPointsLabels: true
#     addServicesLabels: true
#     entryPoint: metrics
