# Traefik Static Configuration
# Configuration for production without SSL

# API and Dashboard
api:
  dashboard: true
  insecure: true  # Dashboard accessible on port 8080

# Entrypoints
entryPoints:
  web:
    address: ":80"
    # Uncomment for HTTPS redirect in the future
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  # websecure:
  #   address: ":443"

# Docker provider
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false  # Only services with traefik.enable=true will be exposed
    network: koprogo-network  # Use the same network as services

# Logging
log:
  level: INFO
  format: common

# Access logs
accessLog:
  format: common

# Metrics (optional)
# metrics:
#   prometheus:
#     addEntryPointsLabels: true
#     addServicesLabels: true
