apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: koprogo
resources:
  - ../../../../_shared/kustomize/base
commonLabels:
  environment: local
patches:
  - path: patches/ingress.yaml
