use crate::application::use_cases::{
    AccountUseCases, AchievementUseCases, AuthUseCases, BoardDashboardUseCases,
    BoardDecisionUseCases, BoardMemberUseCases, BudgetUseCases, BuildingUseCases,
    CallForFundsUseCases, ChallengeUseCases, ChargeDistributionUseCases, ConvocationUseCases,
    DashboardUseCases, DocumentUseCases, EtatDateUseCases, ExpenseUseCases,
    FinancialReportUseCases, GamificationStatsUseCases, GdprUseCases, JournalEntryUseCases,
    LocalExchangeUseCases, MeetingUseCases, NoticeUseCases, NotificationUseCases,
    OwnerContributionUseCases, OwnerUseCases, PaymentMethodUseCases, PaymentReminderUseCases,
    PaymentUseCases, PcnUseCases, QuoteUseCases, ResolutionUseCases, ResourceBookingUseCases,
    SharedObjectUseCases, SkillUseCases, TicketUseCases, UnitOwnerUseCases, UnitUseCases,
};
use crate::infrastructure::audit_logger::AuditLogger;
use crate::infrastructure::email::EmailService;
use crate::infrastructure::pool::DbPool;
use std::sync::Arc;

pub struct AppState {
    pub account_use_cases: Arc<AccountUseCases>,
    pub auth_use_cases: Arc<AuthUseCases>,
    pub building_use_cases: Arc<BuildingUseCases>,
    pub budget_use_cases: Arc<BudgetUseCases>,
    pub unit_use_cases: Arc<UnitUseCases>,
    pub owner_use_cases: Arc<OwnerUseCases>,
    pub unit_owner_use_cases: Arc<UnitOwnerUseCases>,
    pub expense_use_cases: Arc<ExpenseUseCases>,
    pub charge_distribution_use_cases: Arc<ChargeDistributionUseCases>,
    pub meeting_use_cases: Arc<MeetingUseCases>,
    pub convocation_use_cases: Arc<ConvocationUseCases>,
    pub resolution_use_cases: Arc<ResolutionUseCases>,
    pub ticket_use_cases: Arc<TicketUseCases>,
    pub notification_use_cases: Arc<NotificationUseCases>,
    pub payment_use_cases: Arc<PaymentUseCases>,
    pub payment_method_use_cases: Arc<PaymentMethodUseCases>,
    pub quote_use_cases: Arc<QuoteUseCases>,
    pub local_exchange_use_cases: Arc<LocalExchangeUseCases>,
    pub notice_use_cases: Arc<NoticeUseCases>,
    pub resource_booking_use_cases: Arc<ResourceBookingUseCases>,
    pub shared_object_use_cases: Arc<SharedObjectUseCases>,
    pub skill_use_cases: Arc<SkillUseCases>,
    pub document_use_cases: Arc<DocumentUseCases>,
    pub etat_date_use_cases: Arc<EtatDateUseCases>,
    pub pcn_use_cases: Arc<PcnUseCases>,
    pub payment_reminder_use_cases: Arc<PaymentReminderUseCases>,
    pub gdpr_use_cases: Arc<GdprUseCases>,
    pub board_member_use_cases: Arc<BoardMemberUseCases>,
    pub board_decision_use_cases: Arc<BoardDecisionUseCases>,
    pub board_dashboard_use_cases: Arc<BoardDashboardUseCases>,
    pub dashboard_use_cases: Arc<DashboardUseCases>,
    pub financial_report_use_cases: Arc<FinancialReportUseCases>,
    pub owner_contribution_use_cases: Arc<OwnerContributionUseCases>,
    pub call_for_funds_use_cases: Arc<CallForFundsUseCases>,
    pub journal_entry_use_cases: Arc<JournalEntryUseCases>,
    pub achievement_use_cases: Arc<AchievementUseCases>,
    pub challenge_use_cases: Arc<ChallengeUseCases>,
    pub gamification_stats_use_cases: Arc<GamificationStatsUseCases>,
    pub audit_logger: Arc<AuditLogger>,
    pub email_service: Arc<EmailService>,
    pub pool: DbPool, // For seeding operations
}

impl AppState {
    #[allow(clippy::too_many_arguments)]
    pub fn new(
        account_use_cases: AccountUseCases,
        auth_use_cases: AuthUseCases,
        building_use_cases: BuildingUseCases,
        budget_use_cases: BudgetUseCases,
        unit_use_cases: UnitUseCases,
        owner_use_cases: OwnerUseCases,
        unit_owner_use_cases: UnitOwnerUseCases,
        expense_use_cases: ExpenseUseCases,
        charge_distribution_use_cases: ChargeDistributionUseCases,
        meeting_use_cases: MeetingUseCases,
        convocation_use_cases: ConvocationUseCases,
        resolution_use_cases: ResolutionUseCases,
        ticket_use_cases: TicketUseCases,
        notification_use_cases: NotificationUseCases,
        payment_use_cases: PaymentUseCases,
        payment_method_use_cases: PaymentMethodUseCases,
        quote_use_cases: QuoteUseCases,
        local_exchange_use_cases: LocalExchangeUseCases,
        notice_use_cases: NoticeUseCases,
        resource_booking_use_cases: ResourceBookingUseCases,
        shared_object_use_cases: SharedObjectUseCases,
        skill_use_cases: SkillUseCases,
        document_use_cases: DocumentUseCases,
        etat_date_use_cases: EtatDateUseCases,
        pcn_use_cases: PcnUseCases,
        payment_reminder_use_cases: PaymentReminderUseCases,
        gdpr_use_cases: GdprUseCases,
        board_member_use_cases: BoardMemberUseCases,
        board_decision_use_cases: BoardDecisionUseCases,
        board_dashboard_use_cases: BoardDashboardUseCases,
        dashboard_use_cases: DashboardUseCases,
        financial_report_use_cases: FinancialReportUseCases,
        owner_contribution_use_cases: OwnerContributionUseCases,
        call_for_funds_use_cases: CallForFundsUseCases,
        journal_entry_use_cases: JournalEntryUseCases,
        achievement_use_cases: AchievementUseCases,
        challenge_use_cases: ChallengeUseCases,
        gamification_stats_use_cases: GamificationStatsUseCases,
        audit_logger: AuditLogger,
        email_service: EmailService,
        pool: DbPool,
    ) -> Self {
        Self {
            account_use_cases: Arc::new(account_use_cases),
            auth_use_cases: Arc::new(auth_use_cases),
            building_use_cases: Arc::new(building_use_cases),
            budget_use_cases: Arc::new(budget_use_cases),
            unit_use_cases: Arc::new(unit_use_cases),
            owner_use_cases: Arc::new(owner_use_cases),
            unit_owner_use_cases: Arc::new(unit_owner_use_cases),
            expense_use_cases: Arc::new(expense_use_cases),
            charge_distribution_use_cases: Arc::new(charge_distribution_use_cases),
            meeting_use_cases: Arc::new(meeting_use_cases),
            convocation_use_cases: Arc::new(convocation_use_cases),
            resolution_use_cases: Arc::new(resolution_use_cases),
            ticket_use_cases: Arc::new(ticket_use_cases),
            notification_use_cases: Arc::new(notification_use_cases),
            payment_use_cases: Arc::new(payment_use_cases),
            payment_method_use_cases: Arc::new(payment_method_use_cases),
            quote_use_cases: Arc::new(quote_use_cases),
            local_exchange_use_cases: Arc::new(local_exchange_use_cases),
            notice_use_cases: Arc::new(notice_use_cases),
            resource_booking_use_cases: Arc::new(resource_booking_use_cases),
            shared_object_use_cases: Arc::new(shared_object_use_cases),
            skill_use_cases: Arc::new(skill_use_cases),
            document_use_cases: Arc::new(document_use_cases),
            etat_date_use_cases: Arc::new(etat_date_use_cases),
            pcn_use_cases: Arc::new(pcn_use_cases),
            payment_reminder_use_cases: Arc::new(payment_reminder_use_cases),
            gdpr_use_cases: Arc::new(gdpr_use_cases),
            board_member_use_cases: Arc::new(board_member_use_cases),
            board_decision_use_cases: Arc::new(board_decision_use_cases),
            board_dashboard_use_cases: Arc::new(board_dashboard_use_cases),
            dashboard_use_cases: Arc::new(dashboard_use_cases),
            financial_report_use_cases: Arc::new(financial_report_use_cases),
            owner_contribution_use_cases: Arc::new(owner_contribution_use_cases),
            call_for_funds_use_cases: Arc::new(call_for_funds_use_cases),
            journal_entry_use_cases: Arc::new(journal_entry_use_cases),
            achievement_use_cases: Arc::new(achievement_use_cases),
            challenge_use_cases: Arc::new(challenge_use_cases),
            gamification_stats_use_cases: Arc::new(gamification_stats_use_cases),
            audit_logger: Arc::new(audit_logger),
            email_service: Arc::new(email_service),
            pool,
        }
    }
}
