use crate::infrastructure::configure_swagger_ui;
use crate::infrastructure::web::handlers::*;
use actix_web::web;

pub fn configure_routes(cfg: &mut web::ServiceConfig) {
    // OpenAPI Swagger UI (accessible at /swagger-ui/)
    cfg.service(configure_swagger_ui());

    cfg.service(metrics_endpoint);

    cfg.service(
        web::scope("/api/v1")
            .service(health_check)
            // Public Endpoints (no authentication required - Issue #92)
            .service(get_public_syndic_info)
            // Authentication
            .service(login)
            .service(register)
            .service(refresh_token)
            .service(switch_role)
            .service(get_current_user)
            // Buildings
            .service(create_building)
            .service(list_buildings)
            .service(get_building)
            .service(update_building)
            .service(delete_building)
            .service(export_annual_report_pdf) // PDF Export (Issue #47)
            // Units
            .service(create_unit)
            .service(list_units)
            .service(get_unit)
            .service(update_unit)
            .service(delete_unit)
            .service(list_units_by_building)
            .service(assign_owner)
            // Owners
            .service(create_owner)
            .service(list_owners)
            .service(get_owner)
            .service(update_owner)
            .service(link_owner_to_user)
            .service(export_owner_statement_pdf) // PDF Export (Issue #47)
            // Owner Contributions (Revenue)
            .service(create_contribution)
            .service(get_contribution)
            .service(get_contributions_by_owner)
            .service(get_outstanding_contributions)
            .service(record_payment)
            // Call for Funds (Collective payment requests)
            .service(create_call_for_funds)
            .service(get_call_for_funds)
            .service(list_call_for_funds)
            .service(get_overdue_calls)
            .service(send_call_for_funds)
            .service(cancel_call_for_funds)
            .service(delete_call_for_funds)
            // Unit-Owner Relationships
            .service(add_owner_to_unit)
            .service(remove_owner_from_unit)
            .service(update_unit_owner)
            .service(get_unit_owners)
            .service(get_owner_units)
            .service(get_unit_ownership_history)
            .service(get_owner_ownership_history)
            .service(transfer_ownership)
            .service(get_total_ownership_percentage)
            .service(export_ownership_contract_pdf) // PDF Export (Issue #47)
            // Expenses
            .service(create_expense)
            .service(list_expenses)
            .service(get_expense)
            .service(list_expenses_by_building)
            .service(mark_expense_paid)
            .service(mark_expense_overdue)
            .service(cancel_expense)
            .service(reactivate_expense)
            .service(unpay_expense)
            // Invoice Workflow (Issue #73)
            .service(create_invoice_draft)
            .service(update_invoice_draft)
            .service(submit_invoice_for_approval)
            .service(approve_invoice)
            .service(reject_invoice)
            .service(get_pending_invoices)
            .service(get_invoice)
            .service(export_work_quote_pdf) // PDF Export (Issue #47)
            // Charge Distribution (Issue #73)
            .service(calculate_and_save_distribution)
            .service(get_distribution_by_expense)
            .service(get_distributions_by_owner)
            .service(get_total_due_by_owner)
            // Meetings
            .service(create_meeting)
            .service(list_meetings)
            .service(get_meeting)
            .service(list_meetings_by_building)
            .service(update_meeting)
            .service(add_agenda_item)
            .service(complete_meeting)
            .service(cancel_meeting)
            .service(reschedule_meeting)
            .service(delete_meeting)
            .service(export_meeting_minutes_pdf)
            // Convocations (Automatic AG Invitations - Issue #88 - Phase 2)
            .service(create_convocation)
            .service(get_convocation)
            .service(get_convocation_by_meeting)
            .service(list_building_convocations)
            .service(list_organization_convocations)
            .service(delete_convocation)
            .service(schedule_convocation)
            .service(send_convocation)
            .service(cancel_convocation)
            .service(list_convocation_recipients)
            .service(get_convocation_tracking_summary)
            .service(mark_recipient_email_opened)
            .service(update_recipient_attendance)
            .service(set_recipient_proxy)
            .service(send_convocation_reminders)
            // Resolutions & Voting (Issue #46 - Phase 2)
            .service(create_resolution)
            .service(get_resolution)
            .service(list_meeting_resolutions)
            .service(delete_resolution)
            .service(cast_vote)
            .service(list_resolution_votes)
            .service(change_vote)
            .service(close_voting)
            .service(get_meeting_vote_summary)
            // Polls (Board Decision Polls - Issue #51 - Phase 2)
            .service(create_poll)
            .service(get_poll)
            .service(update_poll)
            .service(list_polls)
            .service(find_active_polls)
            .service(publish_poll)
            .service(close_poll)
            .service(cancel_poll)
            .service(delete_poll)
            .service(cast_poll_vote)
            .service(get_poll_results)
            .service(get_poll_building_statistics)
            // Tickets (Maintenance Requests - Issue #85 - Phase 2)
            .service(create_ticket)
            .service(get_ticket)
            .service(list_building_tickets)
            .service(list_organization_tickets)
            .service(list_my_tickets)
            .service(list_assigned_tickets)
            .service(list_tickets_by_status)
            .service(delete_ticket)
            .service(assign_ticket)
            .service(start_work)
            .service(resolve_ticket)
            .service(close_ticket)
            .service(cancel_ticket)
            .service(reopen_ticket)
            .service(get_ticket_statistics)
            .service(get_overdue_tickets)
            // Notifications (Multi-Channel System - Issue #86 - Phase 2)
            .service(create_notification)
            .service(get_notification)
            .service(list_my_notifications)
            .service(list_unread_notifications)
            .service(mark_notification_read)
            .service(mark_all_notifications_read)
            .service(delete_notification)
            .service(get_notification_stats)
            // Notification Preferences
            .service(get_user_preferences)
            .service(get_preference)
            .service(update_preference)
            // Payments (Issue #84 - Phase 2)
            .service(create_payment)
            .service(get_payment)
            .service(get_payment_by_stripe_intent)
            .service(list_owner_payments)
            .service(list_building_payments)
            .service(list_expense_payments)
            .service(list_organization_payments)
            .service(list_payments_by_status)
            .service(list_pending_payments) // Must be before list_failed_payments
            .service(list_failed_payments)
            .service(mark_payment_processing)
            .service(mark_payment_requires_action)
            .service(mark_payment_succeeded)
            .service(mark_payment_failed)
            .service(mark_payment_cancelled)
            .service(refund_payment)
            .service(delete_payment)
            .service(get_owner_payment_stats)
            .service(get_building_payment_stats)
            .service(get_expense_total_paid)
            .service(get_owner_total_paid)
            .service(get_building_total_paid)
            // Payment Methods (Issue #84 - Phase 2)
            .service(create_payment_method)
            .service(get_payment_method)
            .service(get_payment_method_by_stripe_id)
            .service(list_owner_payment_methods)
            .service(list_active_owner_payment_methods)
            .service(get_default_payment_method)
            .service(list_organization_payment_methods)
            .service(list_payment_methods_by_type)
            .service(update_payment_method)
            .service(set_payment_method_as_default)
            .service(deactivate_payment_method)
            .service(reactivate_payment_method)
            .service(delete_payment_method)
            .service(count_active_payment_methods)
            .service(has_active_payment_methods)
            // Quotes (Contractor Quotes Module - Issue #91 - Phase 2)
            .service(create_quote)
            .service(get_quote)
            .service(list_building_quotes)
            .service(list_contractor_quotes)
            .service(list_quotes_by_status)
            .service(submit_quote)
            .service(start_review)
            .service(accept_quote)
            .service(reject_quote)
            .service(withdraw_quote)
            .service(compare_quotes)
            .service(update_contractor_rating)
            .service(delete_quote)
            .service(count_building_quotes)
            .service(count_quotes_by_status)
            // Local Exchanges (SEL - Local Exchange Trading System - Issue #49 - Phase 2)
            .service(create_exchange)
            .service(get_exchange)
            .service(list_building_exchanges)
            .service(list_available_exchanges)
            .service(list_owner_exchanges)
            .service(list_exchanges_by_type)
            .service(request_exchange)
            .service(start_exchange)
            .service(complete_exchange)
            .service(cancel_exchange)
            .service(rate_provider)
            .service(rate_requester)
            .service(delete_exchange)
            .service(get_credit_balance)
            .service(get_leaderboard)
            .service(get_sel_statistics)
            .service(get_owner_summary)
            // Notices (Community Notice Board - Issue #49 - Phase 2)
            .service(create_notice)
            .service(get_notice)
            .service(list_building_notices)
            .service(list_published_notices)
            .service(list_pinned_notices)
            .service(list_notices_by_type)
            .service(list_notices_by_category)
            .service(list_notices_by_status)
            .service(list_author_notices)
            .service(update_notice)
            .service(publish_notice)
            .service(archive_notice)
            .service(pin_notice)
            .service(unpin_notice)
            .service(set_expiration)
            .service(delete_notice)
            .service(get_notice_statistics)
            // Skills (Skills Directory - Issue #49 - Phase 3)
            .service(create_skill)
            .service(get_skill)
            .service(list_building_skills)
            .service(list_available_skills)
            .service(list_free_skills)
            .service(list_professional_skills)
            .service(list_skills_by_category)
            .service(list_skills_by_expertise)
            .service(list_owner_skills)
            .service(update_skill)
            .service(mark_skill_available)
            .service(mark_skill_unavailable)
            .service(delete_skill)
            .service(get_skill_statistics)
            // Shared Objects (Object Sharing Library - Issue #49 - Phase 4)
            .service(create_shared_object)
            .service(get_shared_object)
            .service(list_building_objects)
            .service(list_available_objects)
            .service(list_borrowed_objects)
            .service(list_overdue_objects)
            .service(list_free_objects)
            .service(list_objects_by_category)
            .service(list_owner_objects)
            .service(list_my_borrowed_objects)
            .service(update_shared_object)
            .service(mark_object_available)
            .service(mark_object_unavailable)
            .service(borrow_object)
            .service(return_object)
            .service(delete_shared_object)
            .service(get_object_statistics)
            // Resource Bookings (Resource Booking Calendar - Issue #49 - Phase 5)
            .service(create_booking)
            .service(get_booking)
            .service(list_building_bookings)
            .service(list_by_resource_type)
            .service(list_by_resource)
            .service(list_my_bookings)
            .service(list_my_bookings_by_status)
            .service(list_building_bookings_by_status)
            .service(list_upcoming_bookings)
            .service(list_active_bookings)
            .service(list_past_bookings)
            .service(update_booking)
            .service(cancel_booking)
            .service(complete_booking)
            .service(mark_no_show)
            .service(confirm_booking)
            .service(delete_booking)
            .service(check_conflicts)
            .service(get_booking_statistics)
            // Gamification & Achievements (Issue #49 - Phase 6)
            // Achievements
            .service(create_achievement)
            .service(get_achievement)
            .service(list_achievements)
            .service(list_achievements_by_category)
            .service(list_visible_achievements)
            .service(update_achievement)
            .service(delete_achievement)
            // User Achievements
            .service(award_achievement)
            .service(get_user_achievements)
            .service(get_recent_achievements)
            // Challenges
            .service(create_challenge)
            .service(get_challenge)
            .service(list_challenges)
            .service(list_challenges_by_status)
            .service(list_building_challenges)
            .service(list_active_challenges)
            .service(update_challenge)
            .service(activate_challenge)
            .service(complete_challenge)
            .service(cancel_challenge)
            .service(delete_challenge)
            // Challenge Progress
            .service(get_challenge_progress)
            .service(list_challenge_progress)
            .service(list_user_active_challenges)
            .service(increment_progress)
            // Gamification Stats
            .service(get_gamification_user_stats)
            .service(get_gamification_leaderboard)
            // Board Members
            .service(elect_board_member)
            .service(get_my_mandates) // Must be before get_board_member to avoid UUID parsing
            .service(get_board_dashboard) // Must be before get_board_member to avoid UUID parsing
            .service(get_board_member)
            .service(list_active_board_members)
            .service(list_all_board_members)
            .service(renew_mandate)
            .service(remove_board_member)
            .service(get_board_stats)
            // Board Decisions
            .service(create_decision)
            .service(get_decision)
            .service(list_decisions_by_building)
            .service(list_decisions_by_status)
            .service(list_overdue_decisions)
            .service(update_decision_status)
            .service(add_notes)
            .service(complete_decision)
            .service(get_decision_stats)
            // Documents
            .service(upload_document)
            .service(list_documents)
            .service(get_document)
            .service(download_document)
            .service(list_documents_by_building)
            .service(list_documents_by_meeting)
            .service(list_documents_by_expense)
            .service(link_document_to_meeting)
            .service(link_document_to_expense)
            .service(delete_document)
            // Energy Buying Groups (Achats Groupés d'Énergie - GDPR compliant)
            .service(create_campaign)
            .service(list_campaigns)
            .service(get_campaign)
            .service(get_campaign_stats)
            .service(update_campaign_status)
            .service(delete_campaign)
            .service(add_offer)
            .service(list_offers)
            .service(select_offer)
            .service(finalize_campaign)
            .service(upload_bill)
            .service(get_my_uploads)
            .service(get_upload)
            .service(decrypt_consumption)
            .service(verify_upload)
            .service(delete_upload)
            .service(withdraw_consent)
            .service(get_campaign_uploads)
            // États Datés (Belgian legal requirement for property sales)
            .service(create_etat_date)
            .service(get_etat_date)
            .service(get_by_reference_number)
            .service(list_etats_dates)
            .service(list_etats_dates_by_unit)
            .service(list_etats_dates_by_building)
            .service(mark_in_progress)
            .service(mark_generated)
            .service(mark_delivered)
            .service(update_financial_data)
            .service(update_additional_data)
            .service(list_overdue)
            .service(list_expired)
            .service(get_stats)
            .service(delete_etat_date)
            // Budgets (Annual budget management)
            .service(create_budget)
            .service(get_budget)
            .service(get_budget_by_building_and_fiscal_year)
            .service(get_active_budget)
            .service(list_budgets_by_building)
            .service(list_budgets_by_fiscal_year)
            .service(list_budgets_by_status)
            .service(list_budgets)
            .service(update_budget)
            .service(submit_budget)
            .service(approve_budget)
            .service(reject_budget)
            .service(archive_budget)
            .service(get_budget_stats)
            .service(get_budget_variance)
            .service(delete_budget)
            // Accounts (Belgian PCMN)
            .service(create_account)
            .service(list_accounts)
            .service(get_account)
            .service(get_account_by_code)
            .service(update_account)
            .service(delete_account)
            .service(seed_belgian_pcmn)
            .service(count_accounts)
            // PCN (Belgian Chart of Accounts - Legacy)
            .service(generate_pcn_report)
            .service(export_pcn_pdf)
            .service(export_pcn_excel)
            // Financial Reports (Belgian PCMN)
            .service(generate_balance_sheet)
            .service(generate_income_statement)
            .service(generate_balance_sheet_for_building)
            .service(generate_income_statement_for_building)
            // Journal Entries (Manual Accounting Operations - Noalyss-inspired)
            .service(create_journal_entry)
            .service(list_journal_entries)
            .service(get_journal_entry)
            .service(delete_journal_entry)
            // Dashboard (Accountant)
            .service(get_accountant_stats)
            .service(get_recent_transactions)
            // Payment Reminders (Issue #83)
            // IMPORTANT: Specific routes BEFORE parameterized routes to avoid UUID conflicts
            .service(get_recovery_stats) // Must be before get_reminder (/payment-reminders/stats vs /{id})
            .service(find_overdue_without_reminders) // Must be before get_reminder
            .service(bulk_create_reminders) // Must be before get_reminder
            .service(list_by_organization) // /payment-reminders
            .service(create_reminder) // POST /payment-reminders
            .service(get_reminder) // /payment-reminders/{id}
            .service(delete_reminder) // DELETE /payment-reminders/{id}
            .service(list_by_expense) // /expenses/{id}/payment-reminders
            .service(list_by_owner) // /owners/{id}/payment-reminders
            .service(list_active_by_owner) // /owners/{id}/payment-reminders/active
            .service(mark_as_sent) // PUT /payment-reminders/{id}/mark-sent
            .service(mark_as_opened) // PUT /payment-reminders/{id}/mark-opened
            .service(mark_as_paid) // PUT /payment-reminders/{id}/mark-paid
            .service(cancel_reminder) // PUT /payment-reminders/{id}/cancel
            .service(escalate_reminder) // POST /payment-reminders/{id}/escalate
            .service(add_tracking_number) // PUT /payment-reminders/{id}/tracking-number
            // Seed (SuperAdmin only) - ONE seed only
            .service(seed_demo_data)
            // .service(seed_realistic_data) // Disabled: we only use ONE seed
            .service(clear_demo_data)
            // Stats (SuperAdmin only)
            .service(get_dashboard_stats)
            .service(get_seed_data_stats)
            // Stats (Syndic/Accountant)
            .service(get_syndic_stats)
            .service(get_syndic_urgent_tasks)
            // Stats (Owner)
            .service(get_owner_stats)
            // Organizations (SuperAdmin only)
            .service(list_organizations)
            .service(create_organization)
            .service(update_organization)
            .service(activate_organization)
            .service(suspend_organization)
            .service(delete_organization)
            // Users (SuperAdmin only)
            .service(list_users)
            .service(create_user)
            .service(update_user)
            .service(activate_user)
            .service(deactivate_user)
            .service(delete_user)
            // GDPR (Data Privacy)
            .service(export_user_data)
            .service(erase_user_data)
            .service(can_erase_user)
            // GDPR Complementary Articles (Issue #90)
            .service(rectify_user_data) // Article 16: Right to Rectification
            .service(restrict_user_processing) // Article 18: Right to Restriction
            .service(set_marketing_preference) // Article 21: Right to Object
            // GDPR Admin (SuperAdmin only)
            .service(list_audit_logs)
            .service(admin_export_user_data)
            .service(admin_erase_user_data)
            // Two-Factor Authentication (2FA TOTP - Issue #78)
            .configure(two_factor_handlers::configure_routes)
            // Work Reports (Digital Maintenance Logbook - Issue #134)
            .service(create_work_report)
            .service(get_work_report)
            .service(list_building_work_reports)
            .service(list_organization_work_reports)
            .service(list_work_reports_paginated)
            .service(update_work_report)
            .service(delete_work_report)
            .service(get_active_warranties)
            .service(get_expiring_warranties)
            .service(add_photo)
            .service(add_document)
            // Technical Inspections (Digital Maintenance Logbook - Issue #134)
            .service(create_technical_inspection)
            .service(get_technical_inspection)
            .service(list_building_technical_inspections)
            .service(list_organization_technical_inspections)
            .service(list_technical_inspections_paginated)
            .service(update_technical_inspection)
            .service(delete_technical_inspection)
            .service(get_overdue_inspections)
            .service(get_upcoming_inspections)
            .service(get_inspections_by_type)
            .service(add_report)
            .service(add_inspection_photo)
            .service(add_certificate)
            // IoT Smart Meters (Linky/Ores - Issue #133 - IoT Phase 0)
            .configure(iot_handlers::configure_routes),
    );
}
