use crate::infrastructure::web::handlers::*;
use actix_web::web;

pub fn configure_routes(cfg: &mut web::ServiceConfig) {
    cfg.service(metrics_endpoint);

    cfg.service(
        web::scope("/api/v1")
            .service(health_check)
            // Authentication
            .service(login)
            .service(register)
            .service(refresh_token)
            .service(switch_role)
            .service(get_current_user)
            // Buildings
            .service(create_building)
            .service(list_buildings)
            .service(get_building)
            .service(update_building)
            .service(delete_building)
            // Units
            .service(create_unit)
            .service(list_units)
            .service(get_unit)
            .service(update_unit)
            .service(delete_unit)
            .service(list_units_by_building)
            .service(assign_owner)
            // Owners
            .service(create_owner)
            .service(list_owners)
            .service(get_owner)
            .service(update_owner)
            .service(link_owner_to_user)
            // Unit-Owner Relationships
            .service(add_owner_to_unit)
            .service(remove_owner_from_unit)
            .service(update_unit_owner)
            .service(get_unit_owners)
            .service(get_owner_units)
            .service(get_unit_ownership_history)
            .service(get_owner_ownership_history)
            .service(transfer_ownership)
            .service(get_total_ownership_percentage)
            // Expenses
            .service(create_expense)
            .service(list_expenses)
            .service(get_expense)
            .service(list_expenses_by_building)
            .service(mark_expense_paid)
            .service(mark_expense_overdue)
            .service(cancel_expense)
            .service(reactivate_expense)
            .service(unpay_expense)
            // Invoice Workflow (Issue #73)
            .service(create_invoice_draft)
            .service(update_invoice_draft)
            .service(submit_invoice_for_approval)
            .service(approve_invoice)
            .service(reject_invoice)
            .service(get_pending_invoices)
            .service(get_invoice)
            // Charge Distribution (Issue #73)
            .service(calculate_and_save_distribution)
            .service(get_distribution_by_expense)
            .service(get_distributions_by_owner)
            .service(get_total_due_by_owner)
            // Meetings
            .service(create_meeting)
            .service(list_meetings)
            .service(get_meeting)
            .service(list_meetings_by_building)
            .service(update_meeting)
            .service(add_agenda_item)
            .service(complete_meeting)
            .service(cancel_meeting)
            .service(reschedule_meeting)
            .service(delete_meeting)
            // Board Members
            .service(elect_board_member)
            .service(get_my_mandates) // Must be before get_board_member to avoid UUID parsing
            .service(get_board_dashboard) // Must be before get_board_member to avoid UUID parsing
            .service(get_board_member)
            .service(list_active_board_members)
            .service(list_all_board_members)
            .service(renew_mandate)
            .service(remove_board_member)
            .service(get_board_stats)
            // Board Decisions
            .service(create_decision)
            .service(get_decision)
            .service(list_decisions_by_building)
            .service(list_decisions_by_status)
            .service(list_overdue_decisions)
            .service(update_decision_status)
            .service(add_notes)
            .service(complete_decision)
            .service(get_decision_stats)
            // Documents
            .service(upload_document)
            .service(list_documents)
            .service(get_document)
            .service(download_document)
            .service(list_documents_by_building)
            .service(list_documents_by_meeting)
            .service(list_documents_by_expense)
            .service(link_document_to_meeting)
            .service(link_document_to_expense)
            .service(delete_document)
            // Accounts (Belgian PCMN)
            .service(create_account)
            .service(list_accounts)
            .service(get_account)
            .service(get_account_by_code)
            .service(update_account)
            .service(delete_account)
            .service(seed_belgian_pcmn)
            .service(count_accounts)
            // PCN (Belgian Chart of Accounts - Legacy)
            .service(generate_pcn_report)
            .service(export_pcn_pdf)
            .service(export_pcn_excel)
            // Financial Reports (Belgian PCMN)
            .service(generate_balance_sheet)
            .service(generate_income_statement)
            // Seed (SuperAdmin only) - ONE seed only
            .service(seed_demo_data)
            // .service(seed_realistic_data) // Disabled: we only use ONE seed
            .service(clear_demo_data)
            // Stats (SuperAdmin only)
            .service(get_dashboard_stats)
            .service(get_seed_data_stats)
            // Stats (Syndic/Accountant)
            .service(get_syndic_stats)
            .service(get_syndic_urgent_tasks)
            // Stats (Owner)
            .service(get_owner_stats)
            // Organizations (SuperAdmin only)
            .service(list_organizations)
            .service(create_organization)
            .service(update_organization)
            .service(activate_organization)
            .service(suspend_organization)
            .service(delete_organization)
            // Users (SuperAdmin only)
            .service(list_users)
            .service(create_user)
            .service(update_user)
            .service(activate_user)
            .service(deactivate_user)
            .service(delete_user)
            // GDPR (Data Privacy)
            .service(export_user_data)
            .service(erase_user_data)
            .service(can_erase_user)
            // GDPR Admin (SuperAdmin only)
            .service(list_audit_logs)
            .service(admin_export_user_data)
            .service(admin_erase_user_data),
    );
}
