# Production values for koprogo-api

# Production image
image:
  repository: registry.koprogo.io/api
  tag: "v1.0.0"
  pullPolicy: Always

# Higher replica count for production
replicaCount: 3

# Production resources
resources:
  limits:
    cpu: 2000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

# Aggressive autoscaling for production
autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 50
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: 70

# Production ingress
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rate-limit: "200"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: api.koprogo.io
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: koprogo-api-prod-tls
      hosts:
        - api.koprogo.io

# Production environment variables
env:
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8080"
  RUST_LOG: "info"

# PostgreSQL production configuration
postgresql:
  enabled: true
  auth:
    username: koprogo
    database: koprogo_db
  primary:
    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi
    resources:
      limits:
        cpu: 2000m
        memory: 4Gi
      requests:
        cpu: 500m
        memory: 1Gi
  readReplicas:
    replicaCount: 2
    persistence:
      enabled: true
      storageClass: longhorn
      size: 50Gi
