/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Login and obtain JWT tokens
     * @description Authenticate with email and password to obtain JWT access and refresh tokens.
     *     Returns user roles and active role.
     */
    post: operations["login"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/switch-role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Switch active user role
     * @description Switch between different roles (e.g., Owner → BoardMember).
     *     All subsequent requests will use the new active role.
     */
    post: operations["switchRole"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/me": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get current user profile
     * @description Returns authenticated user information with roles and active role
     */
    get: operations["getCurrentUser"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/buildings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all buildings
     * @description Returns a list of all buildings accessible to the current user
     */
    get: operations["listBuildings"];
    put?: never;
    /**
     * Create a new building
     * @description Create a new building (requires Syndic or SuperAdmin role)
     */
    post: operations["createBuilding"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/buildings/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get building by ID */
    get: operations["getBuildingById"];
    /** Update building */
    put: operations["updateBuilding"];
    post?: never;
    /** Delete building */
    delete: operations["deleteBuilding"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all units */
    get: operations["listUnits"];
    put?: never;
    /** Create a new unit */
    post: operations["createUnit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get unit by ID */
    get: operations["getUnitById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/buildings/{id}/units": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all units in a building */
    get: operations["getUnitsByBuilding"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units/{unit_id}/owners": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get active owners of a unit
     * @description Returns all active owners (end_date is null) of a specific unit
     */
    get: operations["getUnitOwners"];
    put?: never;
    /**
     * Add owner to unit
     * @description Add an owner to a unit with ownership percentage.
     *     Validates that total ownership percentage ≤ 100%.
     */
    post: operations["addOwnerToUnit"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units/{unit_id}/owners/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get ownership history of a unit
     * @description Returns all owners (active and past) of a unit
     */
    get: operations["getUnitOwnershipHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units/{unit_id}/owners/total-percentage": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get total ownership percentage of a unit
     * @description Returns the sum of all active ownership percentages (should be ≤ 1.0)
     */
    get: operations["getTotalOwnershipPercentage"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units/{unit_id}/owners/{owner_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Remove owner from unit
     * @description Ends the ownership relationship by setting end_date to current timestamp
     */
    delete: operations["removeOwnerFromUnit"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/unit-owners/{relationship_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update ownership relationship
     * @description Update ownership percentage or set primary contact
     */
    put: operations["updateUnitOwner"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/units/{unit_id}/owners/transfer": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Transfer ownership between owners
     * @description Transfer ownership from one owner to another.
     *     Automatically closes the old relationship and creates a new one with the same percentage.
     */
    post: operations["transferOwnership"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/owners": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all owners */
    get: operations["listOwners"];
    put?: never;
    /** Create a new owner */
    post: operations["createOwner"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/owners/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get owner by ID */
    get: operations["getOwnerById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/owners/{id}/units": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all active units owned by an owner */
    get: operations["getOwnerUnits"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/owners/{id}/units/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get ownership history of an owner
     * @description Returns all units (active and past) owned by an owner
     */
    get: operations["getOwnerUnitsHistory"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/expenses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List expenses */
    get: operations["listExpenses"];
    put?: never;
    /** Create a new expense */
    post: operations["createExpense"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/expenses/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get expense by ID */
    get: operations["getExpenseById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/expenses/{id}/submit-for-approval": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Submit expense for approval
     * @description Changes status from Draft to PendingApproval.
     *     Expense becomes immutable after submission.
     */
    put: operations["submitExpenseForApproval"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/expenses/{id}/approve": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Approve expense
     * @description Changes status from PendingApproval to Approved.
     *     Requires BoardMember role.
     */
    put: operations["approveExpense"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/expenses/{id}/reject": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Reject expense
     * @description Changes status from PendingApproval to Rejected.
     *     Requires BoardMember role.
     */
    put: operations["rejectExpense"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/expenses/{id}/mark-paid": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Mark expense as paid */
    put: operations["markExpenseAsPaid"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/buildings/{id}/expenses": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get all expenses for a building */
    get: operations["getBuildingExpenses"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List all accounts
     * @description Returns Belgian PCMN accounts for the current organization
     */
    get: operations["listAccounts"];
    put?: never;
    /**
     * Create a new account
     * @description Create a custom PCMN account (requires Accountant role)
     */
    post: operations["createAccount"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get account by ID */
    get: operations["getAccountById"];
    /** Update account */
    put: operations["updateAccount"];
    post?: never;
    /** Delete account */
    delete: operations["deleteAccount"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/code/{code}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get account by PCMN code */
    get: operations["getAccountByCode"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/seed/belgian-pcmn": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Seed Belgian PCMN accounts
     * @description Seeds ~90 standard Belgian PCMN accounts for a new organization.
     *     Should only be called once per organization.
     */
    post: operations["seedBelgianPCMN"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reports/balance-sheet": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Generate balance sheet
     * @description Generate Belgian PCMN balance sheet for a given period
     */
    get: operations["getBalanceSheet"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/reports/income-statement": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Generate income statement
     * @description Generate income statement (compte de résultats) for a given period
     */
    get: operations["getIncomeStatement"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-reminders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List payment reminders */
    get: operations["listPaymentReminders"];
    put?: never;
    /**
     * Create payment reminder
     * @description Create a new payment reminder for an overdue expense.
     *     Belgian late payment penalties (8% annual) are calculated automatically.
     */
    post: operations["createPaymentReminder"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-reminders/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get payment reminder by ID */
    get: operations["getPaymentReminderById"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-reminders/{id}/mark-sent": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Mark reminder as sent */
    put: operations["markReminderAsSent"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-reminders/{id}/escalate": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Escalate reminder to next level
     * @description Automatically escalate reminder to next level:
     *     Gentle → Formal → FinalNotice → LegalAction
     */
    put: operations["escalateReminder"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/payment-reminders/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get payment reminder statistics */
    get: operations["getPaymentReminderStats"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/expenses/{expense_id}/payment-reminders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get reminders for an expense */
    get: operations["getExpenseReminders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/owners/{owner_id}/payment-reminders": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get reminders for an owner */
    get: operations["getOwnerReminders"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/meetings": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List meetings */
    get: operations["listMeetings"];
    put?: never;
    /** Create a new meeting */
    post: operations["createMeeting"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/meetings/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get meeting by ID */
    get: operations["getMeetingById"];
    /** Update meeting */
    put: operations["updateMeeting"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List documents */
    get: operations["listDocuments"];
    put?: never;
    /** Create a new document */
    post: operations["createDocument"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get document by ID */
    get: operations["getDocumentById"];
    put?: never;
    post?: never;
    /** Delete document */
    delete: operations["deleteDocument"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/documents/{id}/download": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Download document file */
    get: operations["downloadDocument"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/gdpr/owners/{owner_id}/data-export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Export owner data (GDPR Art. 15)
     * @description Right of access (GDPR Article 15).
     *     Returns all personal data stored for an owner.
     */
    get: operations["exportOwnerData"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/gdpr/owners/{owner_id}/portable-data": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get portable owner data (GDPR Art. 20)
     * @description Right to data portability (GDPR Article 20).
     *     Returns data in structured, machine-readable format.
     */
    get: operations["getPortableOwnerData"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/gdpr/owners/{owner_id}/delete-data": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete owner data (GDPR Art. 17)
     * @description Right to erasure (GDPR Article 17).
     *     Permanently deletes owner data if no legal obligations prevent it.
     *
     *     **Conditions**:
     *     - No outstanding debts
     *     - No ongoing litigation
     *     - No active ownership
     */
    delete: operations["deleteOwnerData"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health check
     * @description Returns API health status and version
     */
    get: operations["healthCheck"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/metrics": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Prometheus metrics
     * @description Returns Prometheus-formatted metrics for monitoring
     */
    get: operations["getMetrics"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginRequest: {
      /**
       * Format: email
       * @example syndic@example.com
       */
      email: string;
      /**
       * Format: password
       * @example secure_password_123
       */
      password: string;
    };
    LoginResponse: {
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      access_token?: string;
      /** @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9... */
      refresh_token?: string;
      /** @example Bearer */
      token_type?: string;
      /**
       * @description Token expiration in seconds
       * @example 3600
       */
      expires_in?: number;
      roles?: components["schemas"]["UserRole"][];
      /** Format: uuid */
      active_role?: string;
    };
    UserRole: {
      /** Format: uuid */
      role_id?: string;
      /** @enum {string} */
      role_type?:
        | "Owner"
        | "Syndic"
        | "Accountant"
        | "BoardMember"
        | "SuperAdmin";
      /** Format: uuid */
      organization_id?: string;
      organization_name?: string;
    };
    SwitchRoleRequest: {
      /** Format: uuid */
      role_id: string;
    };
    Building: {
      /** Format: uuid */
      id?: string;
      /** @example Résidence Les Érables */
      name?: string;
      /** @example 123 Avenue de Tervuren, 1040 Bruxelles */
      address?: string;
      /** @example 24 */
      total_units?: number;
      /** @example 1985 */
      construction_year?: number;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    CreateBuildingRequest: {
      name: string;
      address: string;
      total_units: number;
      construction_year?: number;
    };
    Unit: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      building_id?: string;
      /** @example 2B */
      unit_number?: string;
      /** @example 2 */
      floor?: number;
      /**
       * Format: double
       * @description Area in square meters
       * @example 85.5
       */
      area?: number;
      /**
       * @example Apartment
       * @enum {string}
       */
      type?: "Apartment" | "Commercial" | "Parking" | "Storage" | "Other";
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    CreateUnitRequest: {
      /** Format: uuid */
      building_id: string;
      unit_number: string;
      floor?: number;
      /** Format: double */
      area?: number;
      /** @enum {string} */
      type?: "Apartment" | "Commercial" | "Parking" | "Storage" | "Other";
    };
    Owner: {
      /** Format: uuid */
      id?: string;
      /** @example Jean Dupont */
      name?: string;
      /**
       * Format: email
       * @example jean.dupont@example.com
       */
      email?: string;
      /** @example +32 2 123 45 67 */
      phone?: string;
      /** @example 123 Avenue de Tervuren, 1040 Bruxelles */
      address?: string;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    CreateOwnerRequest: {
      name: string;
      /** Format: email */
      email: string;
      phone?: string;
      address?: string;
    };
    UnitOwner: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      unit_id?: string;
      /** Format: uuid */
      owner_id?: string;
      /**
       * Format: double
       * @description Ownership percentage (0.0 to 1.0)
       * @example 0.5
       */
      ownership_percentage?: number;
      /** Format: date-time */
      start_date?: string;
      /** Format: date-time */
      end_date?: string | null;
      /** @example true */
      is_primary_contact?: boolean;
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    AddOwnerToUnitRequest: {
      /** Format: uuid */
      owner_id: string;
      /**
       * Format: double
       * @example 0.5
       */
      ownership_percentage: number;
      /** @default false */
      is_primary_contact: boolean;
    };
    TransferOwnershipRequest: {
      /** Format: uuid */
      from_owner_id: string;
      /** Format: uuid */
      to_owner_id: string;
    };
    Expense: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      building_id?: string;
      /** @example Réparation ascenseur - Maintenance annuelle */
      description?: string;
      /**
       * Format: double
       * @example 1250
       */
      amount?: number;
      /**
       * Format: date
       * @example 2025-11-10
       */
      expense_date?: string;
      /**
       * @example Maintenance
       * @enum {string}
       */
      category?:
        | "Maintenance"
        | "Utilities"
        | "Insurance"
        | "ManagementFees"
        | "Repairs"
        | "Improvements"
        | "Legal"
        | "Other";
      /**
       * @example Approved
       * @enum {string}
       */
      status?: "Draft" | "PendingApproval" | "Approved" | "Rejected" | "Paid";
      rejection_reason?: string | null;
      /** @default false */
      paid: boolean;
      line_items?: components["schemas"]["InvoiceLineItem"][];
      /** Format: date-time */
      created_at?: string;
      /** Format: date-time */
      updated_at?: string;
    };
    InvoiceLineItem: {
      /** Format: uuid */
      id?: string;
      /** @example Main d'œuvre technicien */
      description?: string;
      /**
       * Format: double
       * @example 4
       */
      quantity?: number;
      /**
       * Format: double
       * @example 75
       */
      unit_price?: number;
      /**
       * Format: double
       * @description Belgian VAT rates (6%, 12%, 21%)
       * @example 0.21
       * @enum {number}
       */
      vat_rate?: 0.06 | 0.12 | 0.21;
      /**
       * Format: double
       * @example 300
       */
      total_excl_vat?: number;
      /**
       * Format: double
       * @example 63
       */
      vat_amount?: number;
      /**
       * Format: double
       * @example 363
       */
      total_incl_vat?: number;
    };
    CreateExpenseRequest: {
      /** Format: uuid */
      building_id: string;
      description: string;
      /** Format: double */
      amount: number;
      /** Format: date */
      expense_date: string;
      /** @enum {string} */
      category:
        | "Maintenance"
        | "Utilities"
        | "Insurance"
        | "ManagementFees"
        | "Repairs"
        | "Improvements"
        | "Legal"
        | "Other";
      /**
       * @default Draft
       * @enum {string}
       */
      status: "Draft" | "PendingApproval" | "Approved" | "Rejected";
    };
    Account: {
      /** Format: uuid */
      id?: string;
      /**
       * @description PCMN account code
       * @example 451000
       */
      code?: string;
      /** @example TVA à récupérer */
      name?: string;
      /**
       * @example Asset
       * @enum {string}
       */
      account_type?:
        | "Asset"
        | "Liability"
        | "Equity"
        | "Income"
        | "Expense"
        | "OffBalance";
      /** @example 45 */
      parent_code?: string | null;
      /** Format: uuid */
      organization_id?: string;
      /** @default true */
      is_active: boolean;
      /** Format: date-time */
      created_at?: string;
    };
    CreateAccountRequest: {
      code: string;
      name: string;
      /** @enum {string} */
      account_type:
        | "Asset"
        | "Liability"
        | "Equity"
        | "Income"
        | "Expense"
        | "OffBalance";
      parent_code?: string | null;
    };
    BalanceSheet: {
      /** @example 2025 */
      period?: string;
      assets?: {
        fixed_assets?: {
          /** Format: double */
          buildings?: number;
          /** Format: double */
          equipment?: number;
          /** Format: double */
          total?: number;
        };
        current_assets?: {
          /** Format: double */
          receivables?: number;
          /** Format: double */
          bank?: number;
          /** Format: double */
          cash?: number;
          /** Format: double */
          total?: number;
        };
        /** Format: double */
        total_assets?: number;
      };
      liabilities?: {
        equity?: Record<string, never>;
        long_term_liabilities?: Record<string, never>;
        current_liabilities?: Record<string, never>;
        /** Format: double */
        total_liabilities?: number;
      };
      balance_check?: {
        /** Format: double */
        assets?: number;
        /** Format: double */
        liabilities?: number;
        /** Format: double */
        difference?: number;
        balanced?: boolean;
      };
    };
    IncomeStatement: {
      /** @example 2025-Q4 */
      period?: string;
      income?: {
        /** Format: double */
        rental_charges?: number;
        /** Format: double */
        other_income?: number;
        /** Format: double */
        total_income?: number;
      };
      expenses?: {
        /** Format: double */
        property_expenses?: number;
        /** Format: double */
        utilities?: number;
        /** Format: double */
        maintenance?: number;
        /** Format: double */
        management_fees?: number;
        /** Format: double */
        insurance?: number;
        /** Format: double */
        other_expenses?: number;
        /** Format: double */
        total_expenses?: number;
      };
      /** Format: double */
      operating_result?: number;
      /** Format: double */
      financial_result?: number;
      /** Format: double */
      net_result?: number;
    };
    PaymentReminder: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      expense_id?: string;
      /** Format: uuid */
      owner_id?: string;
      /**
       * @description - Gentle: D+15, friendly reminder
       *     - Formal: D+30, formal notice
       *     - FinalNotice: D+45, final warning with penalties
       *     - LegalAction: D+60, legal proceedings
       * @example Gentle
       * @enum {string}
       */
      reminder_level?: "Gentle" | "Formal" | "FinalNotice" | "LegalAction";
      message?: string;
      /** Format: date-time */
      sent_date?: string | null;
      tracking_number?: string | null;
      /**
       * Format: double
       * @description Calculated Belgian late payment penalty (8% annual)
       * @example 13.15
       */
      late_payment_penalty?: number;
      notes?: string;
      /** Format: date-time */
      created_at?: string;
    };
    CreatePaymentReminderRequest: {
      /** Format: uuid */
      expense_id: string;
      /** Format: uuid */
      owner_id: string;
      /** @enum {string} */
      reminder_level: "Gentle" | "Formal" | "FinalNotice" | "LegalAction";
      message?: string;
    };
    Meeting: {
      /** Format: uuid */
      id?: string;
      /** Format: uuid */
      building_id?: string;
      /**
       * @example GeneralAssembly
       * @enum {string}
       */
      meeting_type?:
        | "GeneralAssembly"
        | "BoardMeeting"
        | "ExtraordinaryAssembly";
      /** Format: date-time */
      scheduled_date?: string;
      /** @example Salle communautaire - Rez-de-chaussée */
      location?: string;
      agenda?: string;
      minutes?: string | null;
      /**
       * @default Scheduled
       * @enum {string}
       */
      status: "Scheduled" | "Completed" | "Cancelled";
      /** Format: date-time */
      created_at?: string;
    };
    CreateMeetingRequest: {
      /** Format: uuid */
      building_id: string;
      /** @enum {string} */
      meeting_type:
        | "GeneralAssembly"
        | "BoardMeeting"
        | "ExtraordinaryAssembly";
      /** Format: date-time */
      scheduled_date: string;
      location?: string;
      agenda?: string;
    };
    Document: {
      /** Format: uuid */
      id?: string;
      /** @example Convocation AG - 15 décembre 2025 */
      title?: string;
      /**
       * @example MeetingInvitation
       * @enum {string}
       */
      document_type?:
        | "Invoice"
        | "Contract"
        | "MeetingInvitation"
        | "MeetingMinutes"
        | "InsurancePolicy"
        | "MaintenanceReport"
        | "FinancialReport"
        | "Other";
      /** @example /uploads/convocation-ag-2025-12.pdf */
      file_path?: string;
      /** Format: uuid */
      building_id?: string | null;
      /** Format: uuid */
      expense_id?: string | null;
      /** Format: uuid */
      meeting_id?: string | null;
      /** Format: date-time */
      created_at?: string;
    };
    CreateDocumentRequest: {
      title: string;
      /** @enum {string} */
      document_type:
        | "Invoice"
        | "Contract"
        | "MeetingInvitation"
        | "MeetingMinutes"
        | "InsurancePolicy"
        | "MaintenanceReport"
        | "FinancialReport"
        | "Other";
      file_path: string;
      /** Format: uuid */
      building_id?: string;
      /** Format: uuid */
      expense_id?: string;
      /** Format: uuid */
      meeting_id?: string;
    };
    Error: {
      /** @example Resource not found */
      error?: string;
      /** @example NOT_FOUND */
      code?: string;
      details?: Record<string, never>;
    };
    HealthCheck: {
      /** @example healthy */
      status?: string;
      /** @example 1.0.0 */
      version?: string;
      /** @example connected */
      database?: string;
      /** @example 86400 */
      uptime_seconds?: number;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequest"];
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Invalid credentials */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  switchRole: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SwitchRoleRequest"];
      };
    };
    responses: {
      /** @description Role switched successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example Role switched successfully */
            message?: string;
            active_role?: components["schemas"]["UserRole"];
          };
        };
      };
      /** @description Invalid role ID or unauthorized */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getCurrentUser: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description User profile retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Format: uuid */
            id?: string;
            email?: string;
            name?: string;
            roles?: components["schemas"]["UserRole"][];
            /** Format: uuid */
            active_role?: string;
          };
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  listBuildings: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Buildings retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Building"][];
        };
      };
    };
  };
  createBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBuildingRequest"];
      };
    };
    responses: {
      /** @description Building created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Building"];
        };
      };
      /** @description Invalid input */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBuildingById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Building retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Building"];
        };
      };
      /** @description Building not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  updateBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateBuildingRequest"];
      };
    };
    responses: {
      /** @description Building updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Building"];
        };
      };
      /** @description Building not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Building deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Building not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listUnits: {
    parameters: {
      query?: {
        /** @description Filter by building ID */
        building_id?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Units retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Unit"][];
        };
      };
    };
  };
  createUnit: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateUnitRequest"];
      };
    };
    responses: {
      /** @description Unit created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Unit"];
        };
      };
    };
  };
  getUnitById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Unit retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Unit"];
        };
      };
      /** @description Unit not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getUnitsByBuilding: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Units retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Unit"][];
        };
      };
    };
  };
  getUnitOwners: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        unit_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Owners retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOwner"][];
        };
      };
    };
  };
  addOwnerToUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        unit_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AddOwnerToUnitRequest"];
      };
    };
    responses: {
      /** @description Owner added successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOwner"];
        };
      };
      /** @description Invalid input or total ownership > 100% */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getUnitOwnershipHistory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        unit_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ownership history retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOwner"][];
        };
      };
    };
  };
  getTotalOwnershipPercentage: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        unit_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Total percentage calculated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** Format: uuid */
            unit_id?: string;
            /**
             * Format: double
             * @example 1
             */
            total_percentage?: number;
          };
        };
      };
    };
  };
  removeOwnerFromUnit: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        unit_id: string;
        owner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Owner removed successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Ownership relationship not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateUnitOwner: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        relationship_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          /** Format: double */
          ownership_percentage?: number;
          is_primary_contact?: boolean;
        };
      };
    };
    responses: {
      /** @description Ownership updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOwner"];
        };
      };
      /** @description Invalid input or total ownership > 100% */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  transferOwnership: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        unit_id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransferOwnershipRequest"];
      };
    };
    responses: {
      /** @description Ownership transferred successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOwner"];
        };
      };
      /** @description Owner or unit not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  listOwners: {
    parameters: {
      query?: {
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Owners retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Owner"][];
        };
      };
    };
  };
  createOwner: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOwnerRequest"];
      };
    };
    responses: {
      /** @description Owner created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Owner"];
        };
      };
    };
  };
  getOwnerById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Owner retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Owner"];
        };
      };
      /** @description Owner not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getOwnerUnits: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Units retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOwner"][];
        };
      };
    };
  };
  getOwnerUnitsHistory: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ownership history retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UnitOwner"][];
        };
      };
    };
  };
  listExpenses: {
    parameters: {
      query?: {
        building_id?: string;
        status?: "Draft" | "PendingApproval" | "Approved" | "Rejected" | "Paid";
        category?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Expenses retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"][];
        };
      };
    };
  };
  createExpense: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateExpenseRequest"];
      };
    };
    responses: {
      /** @description Expense created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"];
        };
      };
    };
  };
  getExpenseById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Expense retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"];
        };
      };
      /** @description Expense not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  submitExpenseForApproval: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Expense submitted successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"];
        };
      };
      /** @description Expense not in Draft status */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  approveExpense: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          approval_notes?: string;
        };
      };
    };
    responses: {
      /** @description Expense approved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"];
        };
      };
      /** @description Expense not in PendingApproval status */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Insufficient permissions */
      403: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  rejectExpense: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          rejection_reason: string;
        };
      };
    };
    responses: {
      /** @description Expense rejected successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"];
        };
      };
    };
  };
  markExpenseAsPaid: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Expense marked as paid */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"];
        };
      };
    };
  };
  getBuildingExpenses: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Expenses retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Expense"][];
        };
      };
    };
  };
  listAccounts: {
    parameters: {
      query: {
        organization_id: string;
        account_type?:
          | "Asset"
          | "Liability"
          | "Equity"
          | "Income"
          | "Expense"
          | "OffBalance";
        is_active?: boolean;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accounts retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"][];
        };
      };
    };
  };
  createAccount: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateAccountRequest"];
      };
    };
    responses: {
      /** @description Account created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Invalid input or duplicate code */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAccountById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Account retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Account not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          name?: string;
          is_active?: boolean;
        };
      };
    };
    responses: {
      /** @description Account updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
    };
  };
  deleteAccount: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Account deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Account not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getAccountByCode: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @example 451000 */
        code: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Account retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Account"];
        };
      };
      /** @description Account not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  seedBelgianPCMN: {
    parameters: {
      query: {
        organization_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Accounts seeded successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            /** @example 90 accounts created successfully */
            message?: string;
            /** @example 90 */
            accounts_created?: number;
          };
        };
      };
      /** @description Accounts already seeded */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getBalanceSheet: {
    parameters: {
      query: {
        organization_id: string;
        year: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Balance sheet generated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BalanceSheet"];
          "application/pdf": string;
        };
      };
    };
  };
  getIncomeStatement: {
    parameters: {
      query: {
        organization_id: string;
        year: number;
        quarter?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Income statement generated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["IncomeStatement"];
        };
      };
    };
  };
  listPaymentReminders: {
    parameters: {
      query?: {
        expense_id?: string;
        owner_id?: string;
        reminder_level?: "Gentle" | "Formal" | "FinalNotice" | "LegalAction";
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Payment reminders retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentReminder"][];
        };
      };
    };
  };
  createPaymentReminder: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreatePaymentReminderRequest"];
      };
    };
    responses: {
      /** @description Payment reminder created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentReminder"];
        };
      };
    };
  };
  getPaymentReminderById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Payment reminder retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentReminder"];
        };
      };
      /** @description Payment reminder not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  markReminderAsSent: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": {
          tracking_number?: string;
        };
      };
    };
    responses: {
      /** @description Reminder marked as sent */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentReminder"];
        };
      };
    };
  };
  escalateReminder: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reminder escalated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentReminder"];
        };
      };
      /** @description Already at maximum escalation level */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  getPaymentReminderStats: {
    parameters: {
      query: {
        organization_id: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Statistics retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            total_reminders?: number;
            by_level?: {
              Gentle?: number;
              Formal?: number;
              FinalNotice?: number;
              LegalAction?: number;
            };
            /** Format: double */
            total_penalties?: number;
            /** Format: double */
            recovery_rate?: number;
          };
        };
      };
    };
  };
  getExpenseReminders: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        expense_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reminders retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentReminder"][];
        };
      };
    };
  };
  getOwnerReminders: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Reminders retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaymentReminder"][];
        };
      };
    };
  };
  listMeetings: {
    parameters: {
      query?: {
        building_id?: string;
        status?: "Scheduled" | "Completed" | "Cancelled";
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Meetings retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meeting"][];
        };
      };
    };
  };
  createMeeting: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMeetingRequest"];
      };
    };
    responses: {
      /** @description Meeting created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meeting"];
        };
      };
    };
  };
  getMeetingById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Meeting retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meeting"];
        };
      };
      /** @description Meeting not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  updateMeeting: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": {
          agenda?: string;
          minutes?: string;
          /** @enum {string} */
          status?: "Scheduled" | "Completed" | "Cancelled";
        };
      };
    };
    responses: {
      /** @description Meeting updated successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Meeting"];
        };
      };
    };
  };
  listDocuments: {
    parameters: {
      query?: {
        building_id?: string;
        document_type?: string;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Documents retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Document"][];
        };
      };
    };
  };
  createDocument: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateDocumentRequest"];
      };
    };
    responses: {
      /** @description Document created successfully */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
    };
  };
  getDocumentById: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Document"];
        };
      };
      /** @description Document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  deleteDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  downloadDocument: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Document file */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/pdf": string;
          "application/octet-stream": string;
        };
      };
      /** @description Document not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  exportOwnerData: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data exported successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": {
            owner?: components["schemas"]["Owner"];
            units?: components["schemas"]["UnitOwner"][];
            expenses?: unknown[];
            documents?: unknown[];
            meetings?: unknown[];
          };
        };
      };
    };
  };
  getPortableOwnerData: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Portable data retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  deleteOwnerData: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        owner_id: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Data deleted successfully */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Cannot delete due to legal obligations */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  healthCheck: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description API is healthy */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthCheck"];
        };
      };
    };
  };
  getMetrics: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Metrics retrieved successfully */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/plain": string;
        };
      };
    };
  };
}
