---
# Main playbook - Full cluster deployment

- name: Bootstrap all nodes
  hosts: all
  become: yes
  roles:
    - common

- name: Apply security hardening
  hosts: all
  become: yes
  roles:
    - security

- name: Install K3s control plane
  hosts: k3s_control_plane
  become: yes
  serial: 1
  roles:
    - k3s-server

- name: Install K3s workers
  hosts: k3s_workers
  become: yes
  roles:
    - k3s-agent

- name: Install Longhorn storage
  hosts: k3s_control_plane[0]
  become: yes
  tasks:
    - name: Add Longhorn Helm repository
      command: helm repo add longhorn https://charts.longhorn.io
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Update Helm repositories
      command: helm repo update
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install Longhorn
      command: |
        helm upgrade --install longhorn longhorn/longhorn \
          --namespace longhorn-system \
          --create-namespace \
          --set defaultSettings.defaultDataPath="/var/lib/longhorn" \
          --set persistence.defaultClass=true \
          --set persistence.defaultFsType=ext4 \
          --set persistence.defaultClassReplicaCount=3
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Install ingress controller
  hosts: k3s_control_plane[0]
  become: yes
  tasks:
    - name: Add ingress-nginx Helm repository
      command: helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install ingress-nginx
      command: |
        helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
          --namespace ingress-nginx \
          --create-namespace \
          --set controller.service.type=NodePort \
          --set controller.service.nodePorts.http=30080 \
          --set controller.service.nodePorts.https=30443
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Install cert-manager
  hosts: k3s_control_plane[0]
  become: yes
  tasks:
    - name: Add Jetstack Helm repository
      command: helm repo add jetstack https://charts.jetstack.io
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

    - name: Install cert-manager
      command: |
        helm upgrade --install cert-manager jetstack/cert-manager \
          --namespace cert-manager \
          --create-namespace \
          --set installCRDs=true
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml

- name: Display cluster info
  hosts: k3s_control_plane[0]
  become: yes
  tasks:
    - name: Get cluster info
      command: kubectl cluster-info
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: cluster_info

    - name: Get nodes
      command: kubectl get nodes -o wide
      environment:
        KUBECONFIG: /etc/rancher/k3s/k3s.yaml
      register: nodes_info

    - name: Display info
      debug:
        msg: |
          Cluster deployed successfully!

          {{ cluster_info.stdout }}

          Nodes:
          {{ nodes_info.stdout }}

          Kubeconfig: ~/.kube/koprogo-{{ environment }}
          Access: export KUBECONFIG=~/.kube/koprogo-{{ environment }}
