---
koprogo_branch: production
enable_ssl: true
enable_monitoring: true
enable_backup: true
rust_log: warn
cors_allowed_origins: "https://app.koprogo.be"
frontend_domain: "app.koprogo.be"
api_domain: "api.koprogo.be"
koprogo_domain: "koprogo.be"
acme_email: "admin@koprogo.be"
grafana_admin_password: "{{ vault_grafana_admin_password }}"