#!/bin/bash

# Script pour sauvegarder les variables d'environnement actuelles dans .env
# Usage: ./save-env.sh

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"

echo "=== Sauvegarde des variables OVH dans .env ==="
echo ""

# Vérifier si .env existe déjà
if [ -f "$ENV_FILE" ]; then
    echo "⚠️  Le fichier .env existe déjà!"
    read -p "Voulez-vous le remplacer? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Opération annulée."
        exit 0
    fi
    # Backup de l'ancien fichier
    cp "$ENV_FILE" "$ENV_FILE.backup"
    echo "✓ Backup créé: .env.backup"
fi

# Fonction pour demander une valeur
ask_value() {
    local var_name=$1
    local description=$2
    local current_value="${!var_name}"

    if [ -n "$current_value" ]; then
        echo "✓ $var_name trouvé (${current_value:0:4}***)"
        echo "$var_name=$current_value"
    else
        echo "⚠️  $var_name non défini"
        read -p "Entrez $description: " value
        if [ -n "$value" ]; then
            echo "$var_name=$value"
        else
            echo "# $var_name=your_${var_name,,}_here"
        fi
    fi
}

# Créer le fichier .env
cat > "$ENV_FILE" <<'HEADER'
# OVH Terraform Credentials
# This file is ignored by git for security
# Generated by save-env.sh

HEADER

{
    echo "# OVH API Endpoint"
    ask_value "OVH_ENDPOINT" "OVH endpoint (ex: ovh-eu)"
    echo ""

    echo "# OVH API Credentials"
    echo "# Get these from: https://www.ovh.com/auth/api/createToken"
    ask_value "OVH_APPLICATION_KEY" "OVH Application Key"
    ask_value "OVH_APPLICATION_SECRET" "OVH Application Secret"
    ask_value "OVH_CONSUMER_KEY" "OVH Consumer Key"
    echo ""

    echo "# OVH Cloud Project ID"
    ask_value "OVH_SERVICE_NAME" "OVH Service Name (Project ID)"
} >> "$ENV_FILE"

echo ""
echo "✓ Fichier .env créé avec succès!"
echo ""
echo "Vérifiez le contenu:"
echo "  cat .env"
echo ""
echo "Pour charger les variables:"
echo "  source ./load-env.sh"
echo ""
echo "⚠️  IMPORTANT: Ne committez jamais le fichier .env (déjà dans .gitignore)"
echo ""
