[k3s_master]
koprogo-k8s-integration-master ansible_host=<MASTER_IP> ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[k3s_agents]
# Populated from terraform output

[k3s_cluster:children]
k3s_master
k3s_agents
