#!/bin/bash

# export-github-to-rst.sh
# Exports GitHub issues, milestones, projects, and labels to RST format
# Usage: ./export-github-to-rst.sh

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Output directory
OUTPUT_DIR="docs/github-export"
ISSUES_DIR="$OUTPUT_DIR/issues"
MILESTONES_DIR="$OUTPUT_DIR/milestones"
PROJECTS_DIR="$OUTPUT_DIR/projects"
LABELS_DIR="$OUTPUT_DIR/labels"

echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BLUE}  Exporting GitHub Data to RST${NC}"
echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo ""

# Check if gh CLI is available
if ! command -v gh &> /dev/null; then
    echo -e "${YELLOW}⚠ GitHub CLI (gh) is not installed${NC}"
    echo "Please install it first: make install-deps"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo -e "${YELLOW}⚠ Not authenticated with GitHub CLI${NC}"
    echo "Please run: gh auth login"
    exit 1
fi

# Create directories
mkdir -p "$ISSUES_DIR"/{by-phase,by-priority,by-label}
mkdir -p "$MILESTONES_DIR"
mkdir -p "$PROJECTS_DIR"
mkdir -p "$LABELS_DIR"

# Get repository info
echo -e "${GREEN}📦 Fetching repository information...${NC}"
REPO_INFO=$(gh repo view --json nameWithOwner,description,url)
REPO_NAME=$(echo "$REPO_INFO" | jq -r '.nameWithOwner')
REPO_DESC=$(echo "$REPO_INFO" | jq -r '.description')
REPO_URL=$(echo "$REPO_INFO" | jq -r '.url')

# Export repository overview
echo -e "${GREEN}📝 Creating repository overview...${NC}"
cat > "$OUTPUT_DIR/index.rst" <<EOF
=======================
KoproGo GitHub Overview
=======================

Repository: \`$REPO_NAME <$REPO_URL>\`_

Description
===========

$REPO_DESC

Last Export
===========

:Date: $(date '+%Y-%m-%d %H:%M:%S %Z')
:Generated by: \`\`export-github-to-rst.sh\`\`

Contents
========

.. toctree::
   :maxdepth: 2

   milestones/index
   issues/index
   projects/index
   labels/index

Quick Stats
===========

.. include:: stats.rst

EOF

# Fetch all issues
echo -e "${GREEN}📋 Fetching all issues...${NC}"
ISSUES_JSON=$(gh issue list --limit 1000 --json number,title,state,labels,milestone,createdAt,updatedAt,assignees,body,url --state all)
ISSUE_COUNT=$(echo "$ISSUES_JSON" | jq 'length')
OPEN_COUNT=$(echo "$ISSUES_JSON" | jq '[.[] | select(.state == "OPEN")] | length')
CLOSED_COUNT=$(echo "$ISSUES_JSON" | jq '[.[] | select(.state == "CLOSED")] | length')

echo -e "${BLUE}  Found: $ISSUE_COUNT issues ($OPEN_COUNT open, $CLOSED_COUNT closed)${NC}"

# Fetch milestones
echo -e "${GREEN}🎯 Fetching milestones...${NC}"
MILESTONES_JSON=$(gh api repos/:owner/:repo/milestones --paginate)
MILESTONE_COUNT=$(echo "$MILESTONES_JSON" | jq 'length')

echo -e "${BLUE}  Found: $MILESTONE_COUNT milestones${NC}"

# Fetch labels
echo -e "${GREEN}🏷️  Fetching labels...${NC}"
LABELS_JSON=$(gh label list --limit 1000 --json name,description,color)
LABEL_COUNT=$(echo "$LABELS_JSON" | jq 'length')

echo -e "${BLUE}  Found: $LABEL_COUNT labels${NC}"

# Fetch projects
echo -e "${GREEN}📊 Fetching projects...${NC}"
PROJECTS_JSON=$(gh project list --owner gilmry --limit 100 --format json)
PROJECT_COUNT=$(echo "$PROJECTS_JSON" | jq '.projects | length')

echo -e "${BLUE}  Found: $PROJECT_COUNT projects${NC}"

# Generate stats
cat > "$OUTPUT_DIR/stats.rst" <<EOF
**Total Issues:** $ISSUE_COUNT

**Open Issues:** $OPEN_COUNT

**Closed Issues:** $CLOSED_COUNT

**Milestones:** $MILESTONE_COUNT

**Labels:** $LABEL_COUNT

**Projects:** $PROJECT_COUNT
EOF

# Export Milestones
echo -e "${GREEN}🎯 Exporting milestones...${NC}"
cat > "$MILESTONES_DIR/index.rst" <<EOF
==========
Milestones
==========

Total: $MILESTONE_COUNT milestones

.. toctree::
   :maxdepth: 1

EOF

for i in $(seq 0 $(($MILESTONE_COUNT - 1))); do
    MILESTONE=$(echo "$MILESTONES_JSON" | jq ".[$i]")
    MS_NUMBER=$(echo "$MILESTONE" | jq -r '.number')
    MS_TITLE=$(echo "$MILESTONE" | jq -r '.title')
    MS_DESC=$(echo "$MILESTONE" | jq -r '.description // "No description"')
    MS_STATE=$(echo "$MILESTONE" | jq -r '.state')
    MS_DUE=$(echo "$MILESTONE" | jq -r '.due_on // "No due date"')
    MS_OPEN=$(echo "$MILESTONE" | jq -r '.open_issues')
    MS_CLOSED=$(echo "$MILESTONE" | jq -r '.closed_issues')
    MS_URL=$(echo "$MILESTONE" | jq -r '.html_url')

    # Clean title for filename
    MS_FILENAME=$(echo "$MS_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')

    echo "   milestone-${MS_NUMBER}-${MS_FILENAME}" >> "$MILESTONES_DIR/index.rst"

    # Get issues for this milestone
    MS_ISSUES=$(echo "$ISSUES_JSON" | jq -r --arg title "$MS_TITLE" '[.[] | select(.milestone.title == $title)] | sort_by(.number)')
    MS_ISSUE_COUNT=$(echo "$MS_ISSUES" | jq 'length')

    cat > "$MILESTONES_DIR/milestone-${MS_NUMBER}-${MS_FILENAME}.rst" <<EOF
$(printf '=%.0s' $(seq 1 ${#MS_TITLE}))
$MS_TITLE
$(printf '=%.0s' $(seq 1 ${#MS_TITLE}))

:Number: $MS_NUMBER
:State: $MS_STATE
:Due Date: $MS_DUE
:Open Issues: $MS_OPEN
:Closed Issues: $MS_CLOSED
:Total Issues: $(($MS_OPEN + $MS_CLOSED))
:URL: \`View on GitHub <$MS_URL>\`_

Description
===========

$MS_DESC

Issues ($MS_ISSUE_COUNT)
========

EOF

    if [ "$MS_ISSUE_COUNT" -gt 0 ]; then
        for j in $(seq 0 $(($MS_ISSUE_COUNT - 1))); do
            ISSUE=$(echo "$MS_ISSUES" | jq ".[$j]")
            I_NUMBER=$(echo "$ISSUE" | jq -r '.number')
            I_TITLE=$(echo "$ISSUE" | jq -r '.title')
            I_STATE=$(echo "$ISSUE" | jq -r '.state')
            I_URL=$(echo "$ISSUE" | jq -r '.url')

            STATE_ICON="✅"
            [ "$I_STATE" = "OPEN" ] && STATE_ICON="🔵"

            cat >> "$MILESTONES_DIR/milestone-${MS_NUMBER}-${MS_FILENAME}.rst" <<EOF
$STATE_ICON Issue #$I_NUMBER: $I_TITLE
$(printf -- '-%.0s' $(seq 1 $((${#I_TITLE} + 20))))

:State: $I_STATE
:Link: \`#$I_NUMBER <../issues/issue-${I_NUMBER}.rst>\`_

EOF
        done
    else
        echo "No issues assigned to this milestone yet." >> "$MILESTONES_DIR/milestone-${MS_NUMBER}-${MS_FILENAME}.rst"
    fi
done

# Export Labels
echo -e "${GREEN}🏷️  Exporting labels...${NC}"
cat > "$LABELS_DIR/index.rst" <<EOF
======
Labels
======

Total: $LABEL_COUNT labels

.. list-table::
   :header-rows: 1
   :widths: 30 50 20

   * - Label
     - Description
     - Issues Count
EOF

for i in $(seq 0 $(($LABEL_COUNT - 1))); do
    LABEL=$(echo "$LABELS_JSON" | jq ".[$i]")
    L_NAME=$(echo "$LABEL" | jq -r '.name')
    L_DESC=$(echo "$LABEL" | jq -r '.description // "No description"')
    L_COLOR=$(echo "$LABEL" | jq -r '.color')

    # Count issues with this label
    L_ISSUE_COUNT=$(echo "$ISSUES_JSON" | jq --arg name "$L_NAME" '[.[] | select(.labels[].name == $name)] | length')

    cat >> "$LABELS_DIR/index.rst" <<EOF
   * - **$L_NAME**
     - $L_DESC
     - $L_ISSUE_COUNT
EOF
done

cat >> "$LABELS_DIR/index.rst" <<EOF

Label Categories
================

Phase Labels
------------

.. list-table::
   :header-rows: 1

   * - Label
     - Description
     - Count
EOF

for phase_label in "phase:vps" "phase:k3s" "phase:k8s"; do
    PHASE_COUNT=$(echo "$ISSUES_JSON" | jq --arg label "$phase_label" '[.[] | select(.labels[].name == $label)] | length')
    PHASE_DESC=$(echo "$LABELS_JSON" | jq -r --arg label "$phase_label" '.[] | select(.name == $label) | .description')
    cat >> "$LABELS_DIR/index.rst" <<EOF
   * - **$phase_label**
     - $PHASE_DESC
     - $PHASE_COUNT
EOF
done

cat >> "$LABELS_DIR/index.rst" <<EOF

Priority Labels
---------------

.. list-table::
   :header-rows: 1

   * - Label
     - Description
     - Count
EOF

for prio_label in "priority:critical" "priority:high" "priority:medium" "priority:low"; do
    PRIO_COUNT=$(echo "$ISSUES_JSON" | jq --arg label "$prio_label" '[.[] | select(.labels[].name == $label)] | length')
    PRIO_DESC=$(echo "$LABELS_JSON" | jq -r --arg label "$prio_label" '.[] | select(.name == $label) | .description')
    cat >> "$LABELS_DIR/index.rst" <<EOF
   * - **$prio_label**
     - $PRIO_DESC
     - $PRIO_COUNT
EOF
done

# Export Projects
echo -e "${GREEN}📊 Exporting projects...${NC}"
cat > "$PROJECTS_DIR/index.rst" <<EOF
========
Projects
========

Total: $PROJECT_COUNT projects

.. toctree::
   :maxdepth: 1

EOF

for i in $(seq 0 $(($PROJECT_COUNT - 1))); do
    PROJECT=$(echo "$PROJECTS_JSON" | jq ".projects[$i]")
    P_NUMBER=$(echo "$PROJECT" | jq -r '.number')
    P_TITLE=$(echo "$PROJECT" | jq -r '.title')
    P_DESC=$(echo "$PROJECT" | jq -r '.shortDescription // "No description"')
    P_URL=$(echo "$PROJECT" | jq -r '.url')
    P_ITEMS=$(echo "$PROJECT" | jq -r '.items.totalCount')
    P_FIELDS=$(echo "$PROJECT" | jq -r '.fields.totalCount')
    P_PUBLIC=$(echo "$PROJECT" | jq -r '.public')

    P_FILENAME=$(echo "$P_TITLE" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-//' | sed 's/-$//')

    echo "   project-${P_NUMBER}-${P_FILENAME}" >> "$PROJECTS_DIR/index.rst"

    cat > "$PROJECTS_DIR/project-${P_NUMBER}-${P_FILENAME}.rst" <<EOF
$(printf '=%.0s' $(seq 1 ${#P_TITLE}))
$P_TITLE
$(printf '=%.0s' $(seq 1 ${#P_TITLE}))

:Number: $P_NUMBER
:Public: $P_PUBLIC
:Total Items: $P_ITEMS
:Custom Fields: $P_FIELDS
:URL: \`View on GitHub <$P_URL>\`_

Description
===========

$P_DESC

Statistics
==========

- **Total Items**: $P_ITEMS issues/PRs tracked
- **Custom Fields**: $P_FIELDS custom fields configured

View Details
============

For live project board and detailed status, visit: \`GitHub Project Board <$P_URL>\`_
EOF
done

# Export Issues
echo -e "${GREEN}📋 Exporting issues ($ISSUE_COUNT)...${NC}"

# Create main issues index
cat > "$ISSUES_DIR/index.rst" <<EOF
======
Issues
======

Total: $ISSUE_COUNT issues ($OPEN_COUNT open, $CLOSED_COUNT closed)

.. toctree::
   :maxdepth: 1
   :caption: Browse by:

   by-phase/index
   by-priority/index
   by-label/index

All Issues
==========

.. toctree::
   :maxdepth: 1
   :glob:

   issue-*

EOF

# Export each issue
for i in $(seq 0 $(($ISSUE_COUNT - 1))); do
    ISSUE=$(echo "$ISSUES_JSON" | jq ".[$i]")
    I_NUMBER=$(echo "$ISSUE" | jq -r '.number')
    I_TITLE=$(echo "$ISSUE" | jq -r '.title')
    I_STATE=$(echo "$ISSUE" | jq -r '.state')
    I_BODY=$(echo "$ISSUE" | jq -r '.body // "No description"')
    I_URL=$(echo "$ISSUE" | jq -r '.url')
    I_CREATED=$(echo "$ISSUE" | jq -r '.createdAt')
    I_UPDATED=$(echo "$ISSUE" | jq -r '.updatedAt')
    I_MILESTONE=$(echo "$ISSUE" | jq -r '.milestone.title // "No milestone"')
    I_LABELS=$(echo "$ISSUE" | jq -r '.labels[].name' | paste -sd ", " -)
    I_ASSIGNEES=$(echo "$ISSUE" | jq -r '.assignees[].login' | paste -sd ", " -)

    [ -z "$I_LABELS" ] && I_LABELS="None"
    [ -z "$I_ASSIGNEES" ] && I_ASSIGNEES="Unassigned"

    # Underline for title (RST format)
    TITLE_UNDERLINE=$(printf '=%.0s' $(seq 1 $((${#I_TITLE} + 12))))

    cat > "$ISSUES_DIR/issue-${I_NUMBER}.rst" <<EOF
$TITLE_UNDERLINE
Issue #$I_NUMBER: $I_TITLE
$TITLE_UNDERLINE

:State: **$I_STATE**
:Milestone: $I_MILESTONE
:Labels: $I_LABELS
:Assignees: $I_ASSIGNEES
:Created: $(date -d "$I_CREATED" '+%Y-%m-%d' 2>/dev/null || echo "$I_CREATED")
:Updated: $(date -d "$I_UPDATED" '+%Y-%m-%d' 2>/dev/null || echo "$I_UPDATED")
:URL: \`View on GitHub <$I_URL>\`_

Description
===========

.. raw:: html

   <div class="github-issue-body">

::

$(echo "$I_BODY" | sed 's/^/   /')

.. raw:: html

   </div>

EOF

    # Progress indicator
    if [ $(($i % 10)) -eq 0 ]; then
        echo -e "${BLUE}  Progress: $i/$ISSUE_COUNT${NC}"
    fi
done

# Create by-phase indices
echo -e "${GREEN}📁 Creating phase-based indices...${NC}"
cat > "$ISSUES_DIR/by-phase/index.rst" <<EOF
=================
Issues by Phase
=================

.. toctree::
   :maxdepth: 1

   phase-vps
   phase-k3s
   phase-k8s
   no-phase

EOF

for phase in "phase:vps" "phase:k3s" "phase:k8s"; do
    PHASE_NAME=$(echo "$phase" | cut -d: -f2 | tr '[:lower:]' '[:upper:]')
    PHASE_ISSUES=$(echo "$ISSUES_JSON" | jq --arg phase "$phase" '[.[] | select(.labels[].name == $phase)] | sort_by(.number)')
    PHASE_ISSUE_COUNT=$(echo "$PHASE_ISSUES" | jq 'length')

    cat > "$ISSUES_DIR/by-phase/phase-$(echo $phase | cut -d: -f2).rst" <<EOF
===================
Phase: $PHASE_NAME
===================

Total: $PHASE_ISSUE_COUNT issues

.. toctree::
   :maxdepth: 1

EOF

    for j in $(seq 0 $(($PHASE_ISSUE_COUNT - 1))); do
        I_NUMBER=$(echo "$PHASE_ISSUES" | jq -r ".[$j].number")
        echo "   ../issue-${I_NUMBER}" >> "$ISSUES_DIR/by-phase/phase-$(echo $phase | cut -d: -f2).rst"
    done
done

# No phase
NO_PHASE_ISSUES=$(echo "$ISSUES_JSON" | jq '[.[] | select([.labels[].name] | map(startswith("phase:")) | any | not)] | sort_by(.number)')
NO_PHASE_COUNT=$(echo "$NO_PHASE_ISSUES" | jq 'length')

cat > "$ISSUES_DIR/by-phase/no-phase.rst" <<EOF
==============
No Phase Label
==============

Total: $NO_PHASE_COUNT issues

.. toctree::
   :maxdepth: 1

EOF

for j in $(seq 0 $(($NO_PHASE_COUNT - 1))); do
    I_NUMBER=$(echo "$NO_PHASE_ISSUES" | jq -r ".[$j].number")
    echo "   ../issue-${I_NUMBER}" >> "$ISSUES_DIR/by-phase/no-phase.rst"
done

# Create by-priority indices
echo -e "${GREEN}🎯 Creating priority-based indices...${NC}"
cat > "$ISSUES_DIR/by-priority/index.rst" <<EOF
====================
Issues by Priority
====================

.. toctree::
   :maxdepth: 1

   critical
   high
   medium
   low
   no-priority

EOF

for prio in "priority:critical" "priority:high" "priority:medium" "priority:low"; do
    PRIO_NAME=$(echo "$prio" | cut -d: -f2 | tr '[:lower:]' '[:upper:]')
    PRIO_ISSUES=$(echo "$ISSUES_JSON" | jq --arg prio "$prio" '[.[] | select(.labels[].name == $prio)] | sort_by(.number)')
    PRIO_ISSUE_COUNT=$(echo "$PRIO_ISSUES" | jq 'length')

    cat > "$ISSUES_DIR/by-priority/$(echo $prio | cut -d: -f2).rst" <<EOF
====================
Priority: $PRIO_NAME
====================

Total: $PRIO_ISSUE_COUNT issues

.. toctree::
   :maxdepth: 1

EOF

    for j in $(seq 0 $(($PRIO_ISSUE_COUNT - 1))); do
        I_NUMBER=$(echo "$PRIO_ISSUES" | jq -r ".[$j].number")
        echo "   ../issue-${I_NUMBER}" >> "$ISSUES_DIR/by-priority/$(echo $prio | cut -d: -f2).rst"
    done
done

# No priority
NO_PRIO_ISSUES=$(echo "$ISSUES_JSON" | jq '[.[] | select([.labels[].name] | map(startswith("priority:")) | any | not)] | sort_by(.number)')
NO_PRIO_COUNT=$(echo "$NO_PRIO_ISSUES" | jq 'length')

cat > "$ISSUES_DIR/by-priority/no-priority.rst" <<EOF
==================
No Priority Label
==================

Total: $NO_PRIO_COUNT issues

.. toctree::
   :maxdepth: 1

EOF

for j in $(seq 0 $(($NO_PRIO_COUNT - 1))); do
    I_NUMBER=$(echo "$NO_PRIO_ISSUES" | jq -r ".[$j].number")
    echo "   ../issue-${I_NUMBER}" >> "$ISSUES_DIR/by-priority/no-priority.rst"
done

# Create by-label index (top 10 labels)
echo -e "${GREEN}🏷️  Creating label-based indices...${NC}"
cat > "$ISSUES_DIR/by-label/index.rst" <<EOF
=================
Issues by Label
=================

Top labels by issue count:

.. toctree::
   :maxdepth: 1

EOF

# Get top 10 labels by issue count
for i in $(seq 0 $(($LABEL_COUNT - 1))); do
    L_NAME=$(echo "$LABELS_JSON" | jq -r ".[$i].name")
    L_COUNT=$(echo "$ISSUES_JSON" | jq --arg name "$L_NAME" '[.[] | select(.labels[].name == $name)] | length')
    echo "$L_COUNT $L_NAME"
done | sort -rn | head -10 | while read COUNT NAME; do
    if [ "$COUNT" -gt 0 ]; then
        LABEL_FILENAME=$(echo "$NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g')
        echo "   label-${LABEL_FILENAME}" >> "$ISSUES_DIR/by-label/index.rst"

        LABEL_ISSUES=$(echo "$ISSUES_JSON" | jq --arg name "$NAME" '[.[] | select(.labels[].name == $name)] | sort_by(.number)')

        cat > "$ISSUES_DIR/by-label/label-${LABEL_FILENAME}.rst" <<EOF
$(printf '=%.0s' $(seq 1 $((${#NAME} + 8))))
Label: $NAME
$(printf '=%.0s' $(seq 1 $((${#NAME} + 8))))

Total: $COUNT issues

.. toctree::
   :maxdepth: 1

EOF

        for j in $(seq 0 $(($COUNT - 1))); do
            I_NUMBER=$(echo "$LABEL_ISSUES" | jq -r ".[$j].number")
            echo "   ../issue-${I_NUMBER}" >> "$ISSUES_DIR/by-label/label-${LABEL_FILENAME}.rst"
        done
    fi
done

echo ""
echo -e "${GREEN}✅ Export complete!${NC}"
echo ""
echo -e "${BLUE}📊 Summary:${NC}"
echo -e "  - Issues: $ISSUE_COUNT ($OPEN_COUNT open, $CLOSED_COUNT closed)"
echo -e "  - Milestones: $MILESTONE_COUNT"
echo -e "  - Labels: $LABEL_COUNT"
echo -e "  - Projects: $PROJECT_COUNT"
echo ""
echo -e "${BLUE}📁 Output directory:${NC} $OUTPUT_DIR"
echo -e "${BLUE}📄 Main index:${NC} $OUTPUT_DIR/index.rst"
echo ""
echo -e "${YELLOW}💡 Next steps:${NC}"
echo "  1. Review the generated RST files in $OUTPUT_DIR"
echo "  2. Commit to repository: git add $OUTPUT_DIR && git commit -m 'docs: export GitHub data to RST'"
echo "  3. Optional: Build Sphinx docs with: make docs-sphinx"
echo ""
