#cloud-config
# Cloud-init configuration for KoproGo instances

hostname: ${hostname}

# Package management
package_update: true
package_upgrade: true

packages:
  - curl
  - wget
  - git
  - htop
  - vim
  - net-tools
  - ca-certificates
  - gnupg
  - lsb-release
  - apt-transport-https
  - software-properties-common
  - python3
  - python3-pip
  - jq
  - unzip

# Disable swap (required for K8s)
swap:
  filename: /swapfile
  size: 0
  maxsize: 0

# Timezone
timezone: UTC

# System configuration
runcmd:
  # Set hostname
  - hostnamectl set-hostname ${hostname}

  # Disable swap permanently
  - swapoff -a
  - sed -i '/ swap / s/^/#/' /etc/fstab

  # Configure sysctl for Kubernetes
  - |
    cat > /etc/sysctl.d/99-kubernetes.conf <<EOF
    net.bridge.bridge-nf-call-iptables = 1
    net.bridge.bridge-nf-call-ip6tables = 1
    net.ipv4.ip_forward = 1
    net.ipv4.conf.all.forwarding = 1
    net.ipv6.conf.all.forwarding = 1
    vm.overcommit_memory = 1
    kernel.panic = 10
    kernel.panic_on_oops = 1
    EOF
  - sysctl --system

  # Load kernel modules
  - |
    cat > /etc/modules-load.d/k8s.conf <<EOF
    overlay
    br_netfilter
    EOF
  - modprobe overlay
  - modprobe br_netfilter

  # Increase file limits
  - |
    cat >> /etc/security/limits.conf <<EOF
    * soft nofile 65536
    * hard nofile 65536
    * soft nproc 65536
    * hard nproc 65536
    EOF

  # Configure NTP
  - timedatectl set-ntp true

  # Create ansible user (for configuration management)
  - useradd -m -s /bin/bash -G sudo ansible
  - echo 'ansible ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/ansible

  # Add labels
  - |
    mkdir -p /etc/koprogo
    cat > /etc/koprogo/labels <<EOF
    environment=${environment}
    node_type=${node_type}
    cluster=${cluster_name}
    EOF

# Final message
final_message: "KoproGo ${node_type} node ${hostname} initialized successfully"
