apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: koprogo-integration
resources:
  - ../../../../../_shared/kustomize/base
commonLabels:
  environment: integration
patches:
  - path: patches/ingress.yaml
