apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "koprogo.fullname" . }}-config
  labels:
    {{- include "koprogo.labels" . | nindent 4 }}
data:
  API_DOMAIN: {{ .Values.global.apiDomain }}
  FRONTEND_DOMAIN: {{ .Values.global.domain }}
  TLS_ENABLED: {{ .Values.global.tls.enabled | quote }}
