apiVersion: v1
kind: Service
metadata:
  name: {{ include "koprogo.fullname" . }}-frontend
  labels:
    {{- include "koprogo.labels" . | nindent 4 }}
    {{- include "koprogo.frontend.selectorLabels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "koprogo.frontend.selectorLabels" . | nindent 4 }}
