apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "koprogo.fullname" . }}-frontend
  labels:
    {{- include "koprogo.labels" . | nindent 4 }}
    {{- include "koprogo.frontend.selectorLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "koprogo.frontend.selectorLabels" . | nindent 6 }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        {{- include "koprogo.labels" . | nindent 8 }}
        {{- include "koprogo.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.frontend.serviceAccount.name }}
      securityContext:
        runAsUser: 101
        runAsGroup: 101
        runAsNonRoot: true
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: PUBLIC_API_URL
              value: "{{ if .Values.global.tls.enabled }}https{{ else }}http{{ end }}://{{ .Values.global.apiDomain }}/api/v1"
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: {{ .Values.frontend.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.frontend.healthCheck.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.frontend.healthCheck.path }}
              port: {{ .Values.frontend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
