apiVersion: v1
kind: Secret
metadata:
  name: {{ include "koprogo.fullname" . }}-secrets
  labels:
    {{- include "koprogo.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  jwt-secret: {{ .Values.secrets.jwtSecret | quote }}
  s3-access-key: {{ .Values.secrets.s3AccessKey | quote }}
  s3-secret-key: {{ .Values.secrets.s3SecretKey | quote }}
